### ISSUE TITLE
eolsonde examples conflicts

### ISSUE THREAD

**Issue by garyjg** [NCAR/R-eol#1]
As near as I can tell, the examples in the eolsonde man pages source for project_plots.Rd, readDFile.Rd, and readQCFile.Rd, have some unexpected(?) dependencies.  The plot() calls in readDFile and readQCFile use the plotDir setting set by the project_plots() example.  That used to use "/tmp", but that causes conflicts when different users run the examples on the same system.  I changed it to use tempdir(), but I cannot unlink that in the project_plots.Rd example because then the other plot() calls fail because the plotDir directory does not exist, or so it appears.

**Comment by maclean** [comment]
Committed a change (466b25cf8c6f91) which I believe resolves this issue.  The example now just does `project_plots(plotDir=NULL)` to generate plots on the user's device.  In a \dontrun section (so it isn't run by a code check) is an example of how to save plots to a directory:
`\dontrun{`
`# To save PNG files to a directory`
`project_plots(plotDir="/myplotdir")`
`}`
I don't think this statement is true: "The plot() calls in readDFile and readQCFile use the plotDir setting set by the project_plots() example."  I don't see that.  Those examples should create plots on the current device.
